### ISSUE TITLE
`self` considerations

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/scip-python#13]
- Go-to type definition should take you to the class?
- What should goto definition do?
- What should find references do? Should it show for all references of the same self (i.e. for this class) or just the one for that function?

**Comment by olafurpg** [comment]
I hit on the case where a `self.style` variable in the Textualize/rich repo has 0 definitions so the popover is search-based

![CleanShot 2022-05-26 at 12 58 30@2x](https://user-images.githubusercontent.com/1408093/170475070-34b1d078-0981-4c9e-9033-09ddab9a6bfb.png)

My expectation is that the definition would be the first occurrence in an assignment position (`self.style = ...`).

**Comment by tjdevries** [comment]
fixed by: https://github.com/sourcegraph/scip-python/pull/38
