### ISSUE TITLE
index --no-progerss-bar flag is ignored by some steps

### ISSUE THREAD

**Issue by jlisee** [sourcegraph/scip-python#47]
When I run with `--no-progress-bar` I expect not see controlled or no continous output when writing to a log file instead I see:

> ◜ Evaluating python environment dependencies◠ Evaluating python environment dependencies◝ Evaluating python environment dependencies◞ Evaluating python environment dependencies✔ Evaluating python environment dependencies
> ✔ Parse and search for dependencies
> ◜ Index workspace and track project files◠ Index workspace and track project files◝ Index workspace and track project files....◜ Parse and emit SCIP◠ Parse and emit SCIP◝ Parse and emit SCIP◞ Parse and emit SCIP...

The cause seems to be [explicit calls to `spinner.render()`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/scip-python%24%40b4e352a+spinner.&patternType=literal) like those found here: 

https://github.com/sourcegraph/scip-python/blob/1721c061a6005e5db6b31c77d7900bb1da0d72e7/packages/pyright-scip/src/virtualenv/environment.ts#L43-L52

**Comment by tjdevries** [comment]
I'm thinking of just removing the spinner -- I've been having some trouble with it lately and don't think it's worth it.

Would having a `quiet` mode be OK for you? I think that makes more sense than doing a progress bar for these kinds of things.

**Comment by jlisee** [comment]
That would be useful for some users, but the issue is that you lose context on where the tool died or hung when it runs into trouble.  I think the simplest version would be `--no-spinner` that just prints out each phase as it's started would be a good low effort choice (bonus if it told me how long phase step took or when each phase started), like:

```
(12:27:31) Evaluating python environment dependencies
(12:25:23) Index workspace and track project files
(12:31:56) Parse and emit SCIP
```

-----
**Details**

In a CI context where this will be running my requirements and reasons are as follows:

 1. **Must** make clear what the tool is doing - *helps debug hangs or crashes*
 1. **Must** not produce continuous console output - *keeps build logs usable*
 1. **Should** have each phase reports how long it took - *easier to debug performance changes*
 1. **Should** have each phase reports it's still working every minute or so - *help with hang detection*


----

**Case Study**

The way handles Bazel output works well for this in that we can use [`--curses=no`](https://docs.bazel.build/versions/main/command-line-reference.html#flag--curses) which greatly slows the output rate, and stops using fancy things like a spinner.  Then you can use [`--show_progress_rate_limit=60`](https://docs.bazel.build/versions/main/command-line-reference.html#flag--show_progress_rate_limit) to further control the rate no faster once/60 seconds, and [`--show_timestamps`](https://docs.bazel.build/versions/main/command-line-reference.html#flag--show_timestamps) to get the desired time context.

Which gives something like the following which walks through each phase (loading, analyzing and then execution), provides summary information, and in this case limits it's output rate ~3 mesages/minute.

```
(12:27:31) INFO: Invocation ID: 6ec0bda8-3a53-aeae-a33c-6fd9604b57ad
(12:27:32) INFO: Current date is 2022-07-12
(12:27:32) Loading:
(12:27:32) Loading: 0 packages loaded
(12:27:33) Analyzing: 4938 targets (0 packages loaded, 0 targets configured)
(12:27:33) INFO: Analyzed 4938 targets (0 packages loaded, 0 targets configured).
(12:27:33) INFO: Found 4938 targets...
(12:27:33) [0 / 3,527] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (3 actions, 0 running)
...
(12:28:12) [13,300 / 13,769] RpathPatch external/torch..., 40.5 MiB / 363.8 MiB; 15s remote ... (188 actions, 93 running)
(12:28:18) [17,333 / 19,513] RpathPatch external/torch..., 144.1 MiB / 363.8 MiB; 21s remote ... (182 actions, 88 running)
(12:28:25) [18,061 / 19,666] RpathPatch external/torch..., 157.3 MiB / 363.8 MiB; 28s remote ... (162 actions, 67 running)
...
(12:46:50) INFO: Elapsed time: 1158.332s, Critical Path: 916.26s
(12:46:50) INFO: 84759 processes: 46404 remote cache hit, 27613 internal, 6449 linux-sandbox, 2850 local, 1443 remote.
(12:46:50) INFO: Build completed successfully, 84759 total actions
```

**Comment by tjdevries** [comment]
Hey @jlisee does it look like this PR would meet the needs of what you're thinking: https://github.com/sourcegraph/scip-python/pull/48

I liked several of the options that you mentioned above so I tried to implement them quite similarly for scip-python

**Comment by tjdevries** [comment]
I'll close this for now because I think i've managed to fix everything from the original issue. Let me know if I'm missing anything.
