### ISSUE TITLE
Is there a SCIP to LSIF converter ?

### ISSUE THREAD

**Issue by luochen1990** [sourcegraph/scip-python#82]
Since [Gitlab only support LSIF](https://docs.gitlab.com/ee/user/project/code_intelligence.html), I'm wondering is there a convertor for us to use this project for Gitlab code intelligence ?

**Comment by maks-ivanov** [comment]
This might work: https://github.com/sourcegraph/scip/blob/main/docs/CLI.md#scip-convert
